---
Name: locator
---
Dynamic\Locator\Location:
  extensions:
    - Dynamic\Locator\DistanceDataExtension
    - Dynamic\Locator\AddressDataExtension
    - SilverStripe\Versioned\Versioned('Stage','Live')
