---
Name: locator
---
Dynamic\Locator\Location:
  extensions:
    - Dynamic\Locator\DistanceDataExtension
    - Dynamic\Locator\AddressDataExtension
    - SilverStripe\Versioned\Versioned('Stage','Live')

SilverStripe\GraphQL\Controller:
  schema:
    scaffolding:
      types:
        Dynamic\Locator\Location:
          fields:
            ID: 'The unique identifier of the location'
            Title: 'The title of the location'
            Featured: 'If the location is featured'
            Website: 'The website of the location'
            Phone: 'The phone number of the location'
            Email: 'The email of the location'
            Address: 'The address of the location'
            Address2: 'The second line of the address of the location'
            City: 'The city the location is in'
            State: 'The state the location is in'
            PostalCode: 'The postal code of the location'
            Country: 'The country the location is in'
            Lat: 'The latitude of the location'
            Lng: 'The longitude of the location'
            Category: 'The category of the location'
          operations:
            read:
              resolver: 'Dynamic\Locator\GraphQL\Resolvers\LocationResolver'
              args:
                radius:
                  type: String
                  default: '0'
                  description: 'The radius to look for locations in around address'
                address:
                  type: String
                  description: 'The address to search around'
                featured:
                  type: Boolean
                  description: 'If the locations should be featured'
