---
Name: locator
---
Dynamic\Locator\Location:
  extensions:
    - Dynamic\Locator\DistanceDataExtension
    - Dynamic\Locator\AddressDataExtension
    - SilverStripe\Versioned\Versioned('Stage','Live')

Dynamic\Locator\Locator:
  infoWindowTemplate: 'locator/templates/infowindow-description.html'
  listTemplate: 'locator/templates/location-list-description.html'
